# Generated by Django 4.1.4 on 2022-12-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128, verbose_name='наименование товара')),
                ('description', models.TextField(blank=True, max_length=254, verbose_name='описание')),
                ('photo', models.ImageField(default='/unknowing/default.png', upload_to='product_photo')),
                ('category', models.CharField(max_length=64, verbose_name='категория товара/ тип')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена')),
            ],
        ),
    ]
